#!/bin/bash
# setup git config

git config --global user.email "jamismanwaring@gmail.com"
git config --global user.name "Jamis Johnson"
# turn on colors
git config --global color.ui true
# add aliases
git config --global alias.co checkout
git config --global alias.br branch
git config --global alias.ci commit
git config --global alias.st status
git config --global alias.unstage 'reset HEAD --'
